#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "alltheores", "immersiveengineering", "thermal", "create", "mekanism", "tconstruct", "kubejs", "ae2", "pneumaticcraft", "occultism", "industrialforegoing", "botania"]

